branches:
  only:
    - master
    - ^\d+\.\d+\.\d+(-.+)?$

os:
  - linux
  - windows
  - osx

# dist: xenial

language: python

python:
  - 3.5
  - 3.6
  - pypy3.5

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.7  # See travis issue 10312

    - os: osx
      python: 3.7  # See travis issue 10312

  allow_failures:
    - python: pypy3.5
    - os: osx
    - os: windows

  fast_finish: true

cache: pip

install: make init

script: make ci

notifications:
  email:
    on_success: never
    on_failure: always

stages:
  - Check
  - Test
  - Coverage
  - Build
  - Deploy

jobs:
  include:
    - stage: Check
      script: make check
    - stage: Coverage
      script: make coverage
    - stage: Build
      script: make docs
    - stage: Deploy
      script: make publish